# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: Test

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    test:
        name: >
            ${{ matrix.os.name }} / 
            Node ${{ matrix.node }} / 
            ${{ matrix.pm.name }}@${{ matrix.pm.version }} / 
            Frozen=${{ matrix.frozen-lockfile.name }}

        runs-on: ${{ matrix.os.code }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - name: Linux
                      code: ubuntu-latest
                    - name: macOS
                      code: macos-latest
                    - name: Windows
                      code: windows-latest

                node:
                    - "20.17.0"
                    - "22.9.0"
                    - "24.0.0"
                    - latest

                pm:
                    - name: npm
                      code: npm
                      version: "10.5.0"
                    - name: npm
                      code: npm
                      version: "11.0.0"
                    - name: npm
                      code: npm
                      version: latest

                    - name: Yarn
                      code: yarn
                      version: "4.0.0"
                    - name: Yarn
                      code: yarn
                      version: "4.10.0"
                    - name: Yarn
                      code: yarn
                      version: latest

                    - name: pnpm
                      code: pnpm
                      version: "9.15.0"
                    - name: pnpm
                      code: pnpm
                      version: "10.0.0"
                    - name: pnpm
                      code: pnpm
                      version: latest

                frozen-lockfile:
                    - name: True
                      code: true
                    - name: False
                      code: false

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: ./
              with:
                  node-version: ${{ matrix.node }}
                  package-manager: ${{ matrix.pm.code }}
                  package-manager-version: ${{ matrix.pm.version }}
                  frozen-lockfile: ${{ matrix.frozen-lockfile.code }}

            - name: Validate Node.js version
              if: ${{ matrix.node != 'latest' }}
              shell: bash
              run: |
                  EXPECTED="${{ matrix.node }}"
                  ACTUAL="$(node --version)"

                  ACTUAL="${ACTUAL#v}"

                  if [ "$EXPECTED" != "$ACTUAL" ]; then
                      echo "Expected node@$EXPECTED, but got node@$ACTUAL"
                      exit 1
                  fi

            - name: Validate package manager version
              if: ${{ matrix.pm.version != 'latest' }}
              shell: bash
              run: |
                  EXPECTED="${{ matrix.pm.version }}"
                  ACTUAL="$(${{ matrix.pm.code }} --version)"

                  ACTUAL="${ACTUAL#v}"

                  if [ "$EXPECTED" != "$ACTUAL" ]; then
                      echo "Expected ${{ matrix.pm.code }}@$EXPECTED, but got ${{ matrix.pm.code }}@$ACTUAL"
                      exit 1
                  fi
